# Generated by Django 3.0.8 on 2020-07-25 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcbn_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
