version: "3"

services:
  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file: .env
  web:
    image: wcbn:latest
    build: .
    volumes:
      - ./src/:/code
    ports:
      - "8000:8000"
    env_file: .env
    depends_on:
      - db
    stdin_open: true
    tty: true
