# Generated by Django 3.0.8 on 2020-07-25 04:19

from django.db import migrations, models
import django.utils.timezone
import wcbn_util.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', wcbn_util.fields.CharField(max_length=65000)),
                ('text', models.TextField()),
                ('author', wcbn_util.fields.CharField(max_length=65000)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='article_images')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'articles',
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', wcbn_util.fields.CharField(max_length=65000)),
                ('summary', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='concert_images')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('door_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location_name', wcbn_util.fields.CharField(blank=True, max_length=65000, null=True)),
                ('location_address', wcbn_util.fields.CharField(blank=True, max_length=65000, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('age_restriction', wcbn_util.fields.CharField(blank=True, max_length=65000, null=True)),
                ('is_presented_by_wcbn', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'concerts',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('title', wcbn_util.fields.CharField(max_length=65000)),
                ('summary', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='event_images')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location_name', wcbn_util.fields.CharField(blank=True, max_length=65000, null=True)),
                ('location_address', wcbn_util.fields.CharField(blank=True, max_length=65000, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('age_restriction', wcbn_util.fields.CharField(blank=True, max_length=65000, null=True)),
                ('is_presented_by_wcbn', models.BooleanField(default=False)),
                ('is_free', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'events',
            },
        ),
    ]
