# Generated by Django 3.0.8 on 2020-07-27 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcbn_cms', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='concert',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Free?'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='is_presented_by_wcbn',
            field=models.BooleanField(default=False, verbose_name='Presented by WCBN?'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=False, verbose_name='Free?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='is_presented_by_wcbn',
            field=models.BooleanField(default=False, verbose_name='Presented by WCBN?'),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, null=True, verbose_name='URL'),
        ),
    ]
