# Generated by Django 3.0.8 on 2020-08-02 03:34

from django.db import migrations, models
import wcbn_util.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wcbn_cms', '0002_auto_20200727_0817'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='featured_image_alt_text',
            field=wcbn_util.fields.CharField(default='an image', max_length=65000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(default='/media/article_images/vonlmo.png', upload_to='article_images'),
            preserve_default=False,
        ),
    ]
