# Generated by Django 3.0.8 on 2020-07-05 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcbn_cms', '0002_article_featured_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('summary', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='concert_images')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('door_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=140, null=True)),
                ('location_address', models.CharField(blank=True, max_length=140, null=True)),
                ('url', models.URLField(blank=True, max_length=140, null=True)),
                ('age_restriction', models.CharField(blank=True, max_length=20, null=True)),
                ('presented_by_wcbn', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('summary', models.TextField()),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='event_images')),
                ('start_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('location_name', models.CharField(blank=True, max_length=140, null=True)),
                ('location_address', models.CharField(blank=True, max_length=140, null=True)),
                ('url', models.URLField(blank=True, max_length=140, null=True)),
                ('age_restriction', models.CharField(blank=True, max_length=20, null=True)),
                ('presented_by_wcbn', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterField(
            model_name='article',
            name='featured_image',
            field=models.ImageField(blank=True, null=True, upload_to='article_images'),
        ),
    ]
