# Generated by Django 3.0.8 on 2020-08-02 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wcbn_cms', '0003_auto_20200802_0334'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='featured_image_alt_text',
            new_name='featured_image_caption',
        ),
    ]
