# Generated by Django 3.0.8 on 2020-07-25 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wcbn_cms', '0004_auto_20200725_0343'),
    ]

    operations = [
        migrations.AddField(
            model_name='concert',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='event',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
