# Generated by Django 3.0.8 on 2020-08-02 06:06

from django.db import migrations
import wcbn_util.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wcbn_cms', '0004_auto_20200802_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='author',
            field=wcbn_util.fields.CharField(blank=True, default='WCBN Staff', max_length=65000),
        ),
    ]
