# Generated by Django 3.0.8 on 2020-07-25 04:09

from django.db import migrations, models
import django.utils.timezone
import wcbn_util.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wcbn_cms', '0005_auto_20200725_0358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='concert',
            old_name='presented_by_wcbn',
            new_name='is_presented_by_wcbn',
        ),
        migrations.RenameField(
            model_name='event',
            old_name='presented_by_wcbn',
            new_name='is_presented_by_wcbn',
        ),
        migrations.AddField(
            model_name='article',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='concert',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='concert',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AddField(
            model_name='event',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='event',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=wcbn_util.fields.CharField(max_length=65000),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=wcbn_util.fields.CharField(max_length=65000),
        ),
        migrations.AlterField(
            model_name='concert',
            name='age_restriction',
            field=wcbn_util.fields.CharField(blank=True, max_length=65000, null=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='location_address',
            field=wcbn_util.fields.CharField(blank=True, max_length=65000, null=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='location_name',
            field=wcbn_util.fields.CharField(blank=True, max_length=65000, null=True),
        ),
        migrations.AlterField(
            model_name='concert',
            name='title',
            field=wcbn_util.fields.CharField(max_length=65000),
        ),
        migrations.AlterField(
            model_name='concert',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='age_restriction',
            field=wcbn_util.fields.CharField(blank=True, max_length=65000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_address',
            field=wcbn_util.fields.CharField(blank=True, max_length=65000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='location_name',
            field=wcbn_util.fields.CharField(blank=True, max_length=65000, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='title',
            field=wcbn_util.fields.CharField(max_length=65000),
        ),
        migrations.AlterField(
            model_name='event',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
